# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "aircraft_types", :force => true do |t|
    t.column "type_name", :text, :null => false
    t.column "passenger_capacity", :integer, :null => false
    t.column "picture", :integer
    t.column "sort_value", :integer, :default => 0
  end

  create_table "aircrafts", :force => true do |t|
    t.column "aircraft_type", :integer, :null => false
    t.column "identifier", :text, :null => false
    t.column "equipment_description", :text
    t.column "picture", :integer
    t.column "type_equip", :text
    t.column "color", :text
    t.column "prioritized", :boolean
    t.column "deleted", :boolean, :default => false
    t.column "office", :integer
    t.column "hourly_rate", :float, :default => 50.0
    t.column "hobbs", :float, :default => 0.0, :null => false
    t.column "tach", :float, :default => 0.0, :null => false
  end

  create_table "billing_charges", :force => true do |t|
    t.column "created_at", :datetime
    t.column "created_by", :integer, :null => false
    t.column "refers_to", :integer
    t.column "charge_type", :text
    t.column "flight_date", :date
    t.column "user_id", :integer, :null => false
    t.column "instructor_id", :integer
    t.column "aircraft_id", :integer
    t.column "hobbs_start", :float
    t.column "hobbs_end", :float
    t.column "tach_end", :float
    t.column "aircraft_rate", :float
    t.column "instructor_rate", :float
    t.column "charge_amount", :float, :null => false
    t.column "running_total", :float
    t.column "notes", :text
  end

  create_table "documents", :force => true do |t|
    t.column "refers_to", :integer
    t.column "created_by", :integer, :null => false
    t.column "last_updated_by", :integer, :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
    t.column "mime_type", :text, :null => false
    t.column "one_line_summary", :text, :null => false
    t.column "body", :text, :null => false
    t.column "document_type", :text, :null => false
    t.column "status", :text, :null => false
    t.column "url_name", :text
    t.column "flight_plan", :text
  end

  add_index "documents", ["refers_to", "url_name"], :name => "document_url_index", :unique => true

  create_table "documents_audit", :force => true do |t|
    t.column "refers_to", :integer
    t.column "created_by", :integer
    t.column "last_updated_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "mime_type", :text
    t.column "one_line_summary", :text
    t.column "body", :text
    t.column "document_type", :text
    t.column "status", :text
    t.column "url_name", :text
    t.column "flight_plan", :text
    t.column "version", :integer
  end

  create_table "documents_reservations", :id => false, :force => true do |t|
    t.column "reservation_id", :integer, :null => false
    t.column "document_id", :integer, :null => false
  end

  create_table "extra_user_infos", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "birthdate", :date
    t.column "is_us_citizen", :boolean, :null => false
    t.column "primary_phone_id", :integer
    t.column "primary_address_id", :integer
    t.column "portrait_id", :integer
    t.column "user_biography", :text
    t.column "is_contact_info_shared", :boolean, :default => true
    t.column "faa_physical_date", :date
    t.column "last_biennial_or_certificate_date", :date
    t.column "birthdate_approved", :boolean, :default => true
    t.column "physical_approved", :boolean, :default => true
  end

  add_index "extra_user_infos", ["user_id"], :name => "extra_user_infos_user_id_key", :unique => true

  create_table "groups", :force => true do |t|
    t.column "group_name", :text, :null => false
    t.column "group_type", :text, :null => false
  end

  add_index "groups", ["group_name"], :name => "groups_group_name_key", :unique => true

  create_table "groups_users", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "group_id", :integer, :null => false
    t.column "approved", :boolean, :default => false
  end

  add_index "groups_users", ["user_id", "group_id"], :name => "groups_users_index", :unique => true

  create_table "images", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "image_binary", :binary, :null => false
    t.column "thumbnail", :binary, :null => false
    t.column "image_type", :text, :null => false
    t.column "created_at", :datetime, :null => false
    t.column "caption", :text
  end

  create_table "maintenance_dates", :force => true do |t|
    t.column "aircraft_id", :integer, :null => false
    t.column "expires", :integer, :null => false
    t.column "description", :text, :null => false
    t.column "comments", :text
  end

  create_table "offices", :force => true do |t|
    t.column "name", :text
  end

  create_table "reservation_rules", :force => true do |t|
    t.column "description", :text, :null => false
    t.column "code", :text, :null => false
  end

  create_table "reservation_rules_exceptions", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "reservation_rule_id", :integer, :null => false
    t.column "expiration_time", :datetime
  end

  create_table "reservations", :force => true do |t|
    t.column "created_by", :integer, :null => false
    t.column "aircraft_id", :integer
    t.column "instructor_id", :integer
    t.column "time_start", :datetime, :null => false
    t.column "time_end", :datetime, :null => false
    t.column "reservation_type", :text, :null => false
    t.column "status", :text, :null => false
  end

  create_table "reservations_changes", :force => true do |t|
    t.column "created_by", :integer
    t.column "aircraft_id", :integer
    t.column "instructor_id", :integer
    t.column "time_start", :datetime
    t.column "time_end", :datetime
    t.column "reservation_type", :text
    t.column "status", :text
    t.column "sent", :boolean, :default => true
  end

  create_table "user_addresses", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "address_line1", :text, :null => false
    t.column "address_line2", :text
    t.column "city", :text, :null => false
    t.column "state_province", :text
    t.column "postal_code", :text
    t.column "country", :text
  end

  create_table "user_certificates", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "approved", :boolean, :default => false
    t.column "certificate_category", :text, :null => false
    t.column "airplane_sel_rating", :boolean, :default => false
    t.column "airplane_mel_rating", :boolean, :default => false
    t.column "helicopter_rating", :boolean, :default => false
    t.column "instrument_rating", :boolean, :default => false
  end

  create_table "user_phone_numbers", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "phone_number", :text, :null => false
    t.column "is_txt_capable", :boolean
  end

  create_table "users", :force => true do |t|
    t.column "email", :text, :null => false
    t.column "first_names", :text, :null => false
    t.column "last_name", :text, :null => false
    t.column "created_from_legacy_data", :boolean, :default => false
    t.column "email_verified", :boolean, :default => false
    t.column "account_suspended", :boolean, :default => false
    t.column "salted_password", :text, :null => false
    t.column "salt", :string, :limit => 40, :null => false
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "created_at", :datetime, :null => false
    t.column "last_login", :datetime
    t.column "office", :integer
    t.column "hourly_rate", :float, :default => 50.0
  end

  add_index "users", ["email"], :name => "users_email_key", :unique => true

end
