development:
  adapter: postgresql
  database: devel
  username: postgres
  password: test

test:
    adapter: postgresql
    database: test
    username: postgres
    password: test

production:
    adapter: postgresql
    database: devel
    username: postgres
    password: test
